//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acessopeliculas
{
    using System;
    using System.Collections.Generic;
    
    public partial class peliculas
    {
        public int id_peli { get; set; }
        public string nombre { get; set; }
        public System.DateTime año { get; set; }
        public string director { get; set; }
        public string genere { get; set; }
        public string protag { get; set; }
    }
}
